- hosts: targets
  sudo: yes
  tasks:
   - name: install python3
     apt: pkg=python3 state=installed update_cache=true
   - name: install python3-pip
     apt: pkg=python3-pip state=installed update_cache=true
   - name: install git
     apt: pkg=git state=installed update_cache=true
   - name: get clone nofreelunch
     git: repo=git://github.com/GINK03/www-nofreelunch.git 
       dest=/home/vagrant/www-nofreelunch
       force=yes
   - name: install pip3 install flask
     shell: "pip3 install flask"
   - name: install pip3 install regex
     shell: "pip3 install regex"
   - name: install pip3 install chainer
     shell: "pip3 install chainer"
   
