- hosts:
  - 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
    - name: Provision a set of instances
      local_action: ec2
          keypair={{keypair}}
          group={{group}}
          instance_type={{instance_type}}
          image={{image}}
          region={{region}}
          wait={{wait}}
      register: ec2
